import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/elements/header/Navbar";
import Footer from "@/components/elements/footer/Footer";
import { newOrder } from "./font";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${newOrder.variable} font-neworder antialiased `}
      >
        <Navbar/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
